### ISSUE TITLE
Game crash when open console.

### ISSUE THREAD

**Issue by lukenYang** [yamashi/CyberEngineTweaks#280] opened 2020-12-24 15:19 UTC
cyber_engine_tweaks.log
[2020-12-24 23:16:12.188] [info] Game version 1.06
[2020-12-24 23:16:12.223] [info] 	AMD SMT Patch: success
**[2020-12-24 23:16:12.223] [warning] 	Spectre patch: failed, unknown version**
**[2020-12-24 23:16:12.236] [warning] 	Virtual Input Patch: failed**
[2020-12-24 23:16:12.280] [info] 	Start screen patch: success
[2020-12-24 23:16:12.283] [info] 	Disable intro movies patch: success
[2020-12-24 23:16:12.358] [info] 	Hidden options hook: success
[2020-12-24 23:16:12.393] [info] 	Hook mouse clip function!
[2020-12-24 23:16:12.421] [info] 	Log function hook complete!
[2020-12-24 23:16:12.450] [info] 	LogChannel function hook complete!
[2020-12-24 23:16:12.524] [info] 	TDBID::ctor function hook complete!
[2020-12-24 23:16:12.599] [info] 	TDBID::ctor[CString] function hook complete!
[2020-12-24 23:16:12.673] [info] 	TDBID::ctor[Derive] function hook complete!
[2020-12-24 23:16:12.747] [info] 	TDBID::ctor[Unknown] function hook complete!
[2020-12-24 23:16:12.786] [info] 	TDBID::ToStringDEBUG function hook complete!
[2020-12-24 23:16:13.240] [info] 	D3D12 hook complete

stacktrace.txt
Error reason: Unhandled exception
Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x0.
File: <Unknown>(0)

report.txt
Version=1
EventType=REDEngineErrorReport
EventTime=0
ReportIdentifier=ffffffff-ffffffff-00000001-00000000
Sig[0].Name=StackHash
Sig[0].Value=0x0000000000000000
Sig[1].Name=ErrorReason
Sig[1].Value=Unhandled exception
Sig[2].Name=InternalVersion
Sig[2].Value=3.0.3235023  P4CL: 4177747  Stream: //R6.Root/R6.Patch0Hotfix2 
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.18363.2.0.0.256.1

**Comment by psychomax13** [comment] 2020-12-24 16:57
The same. Just crashed on 1.06.

Here is the log.

`[2020-12-24 18:55:32.557] [info] Game version 1.06
[2020-12-24 18:55:32.722] [info] 	AMD SMT Patch: success
[2020-12-24 18:55:32.722] [warning] 	Spectre patch: failed, unknown version
[2020-12-24 18:55:32.751] [warning] 	Virtual Input Patch: failed
[2020-12-24 18:55:32.796] [info] 	Start screen patch: success
[2020-12-24 18:55:32.799] [info] 	Disable intro movies patch: success
[2020-12-24 18:55:32.862] [info] 	Hidden options hook: success
[2020-12-24 18:55:32.884] [info] 	Hook mouse clip function!
[2020-12-24 18:55:32.899] [info] 	Log function hook complete!
[2020-12-24 18:55:32.915] [info] 	LogChannel function hook complete!
[2020-12-24 18:55:32.977] [info] 	TDBID::ctor function hook complete!
[2020-12-24 18:55:33.039] [info] 	TDBID::ctor[CString] function hook complete!
[2020-12-24 18:55:33.102] [info] 	TDBID::ctor[Derive] function hook complete!
[2020-12-24 18:55:33.164] [info] 	TDBID::ctor[Unknown] function hook complete!
[2020-12-24 18:55:33.190] [info] 	TDBID::ToStringDEBUG function hook complete!
[2020-12-24 18:55:33.665] [info] 	D3D12 hook complete`

**Comment by dwasss** [comment] 2020-12-24 17:58
Also see https://github.com/yamashi/CyberEngineTweaks/issues/283

**Comment by WSSDude420** [comment] 2020-12-24 20:57
Do you have some other software running that hooks to programs?

Steam overlay, something?

For me, crash is caused when RivaTuner Server Statistics is running... Turning it off fixes it...
So maybe try to look what is running in the background that could potentially hook to the game, like said overlays.

#267

**Comment by psychomax13** [comment] 2020-12-24 21:25
Yeah, i see now. I got RivaTuner Server as well. Thanks.

**Comment by lukenYang** [comment] 2020-12-25 02:27
> Do you have some other software running that hooks to programs?
> 
> Steam overlay, something?
> 
> For me, crash is caused when RivaTuner Statistics Server is running... Turning it off fixes it...
> So maybe try to look what is running in the background that could potentially hook to the game, like said overlays.
> 
> #267
> 
> This is not ideal tbh at all that this happens, but whatever...
> Seems to be problem of when this DLL hooks. You can read it up at linked issue...

Yes, i had steam overlay,msi afterburner.
When i close afterburner, console is fine!
Thank you.

**Comment by TheChief5055** [comment] 2020-12-25 06:24
Same problem here:

`[2020-12-25 10:16:20.660] [info] Game version 1.06
[2020-12-25 10:16:20.698] [info] 	AMD SMT Patch: success
[2020-12-25 10:16:20.698] [warning] 	Spectre patch: failed, unknown version
[2020-12-25 10:16:20.711] [warning] 	Virtual Input Patch: failed
[2020-12-25 10:16:20.753] [info] 	Start screen patch: success
[2020-12-25 10:16:20.756] [info] 	Disable intro movies patch: success
[2020-12-25 10:16:20.816] [info] 	Hidden options hook: success
[2020-12-25 10:16:20.838] [info] 	Hook mouse clip function!
[2020-12-25 10:16:20.854] [info] 	Log function hook complete!
[2020-12-25 10:16:20.870] [info] 	LogChannel function hook complete!
[2020-12-25 10:16:20.930] [info] 	TDBID::ctor function hook complete!
[2020-12-25 10:16:20.990] [info] 	TDBID::ctor[CString] function hook complete!
[2020-12-25 10:16:21.050] [info] 	TDBID::ctor[Derive] function hook complete!
[2020-12-25 10:16:21.111] [info] 	TDBID::ctor[Unknown] function hook complete!
[2020-12-25 10:16:21.138] [info] 	TDBID::ToStringDEBUG function hook complete!
[2020-12-25 10:16:21.282] [info] 	D3D12 hook complete
`

1.06 with latest console release. Latest AMD drivers. 1.05 has no problem with prev. console release.

**Comment by WSSDude420** [comment] 2020-12-25 11:53
Should be fixed to an extent with upcoming release now.

Note though that you should follow this comment for RTSS to work reliably (otherwise, console works half the time and other half is not rendering, depending on which hook was faster...)
https://github.com/yamashi/CyberEngineTweaks/issues/245#issuecomment-750009640

Working on revising whole DX12 hooking procedure now, so hopefully, we will have some more robust solution in place SOON™ which would not require similar stunts from user.

**Comment by TheChief5055** [comment] 2020-12-25 11:57
Oh, I've forgot to say: my videocard is Radeon RX480, so no RTSS and no RivaTuner here.

**Comment by WSSDude420** [comment] 2020-12-25 12:03
Still could help. 

But if it is reproducible for you, if you can, package up latest crash report.
Follow instructions found here https://github.com/yamashi/CyberEngineTweaks/issues/12 (but please, package whole folder to zip... easier to search for loaded modules and such this way)

Could be you have something else, there seems to be some general problem with other apps/dlls that hook to the game. Could as well crash with OBS, who knows, did not try all combinations...
Or maybe we have some completely new, unique error on our hands...

If AMD has some overlay like NVIDIA has, could be that overlay is the cause of a crash... All you need for this case are GPU drivers, as these come packaged by default usually. Do not have AMD gpu at hand though so hard to judge if this is the case now... Just assumptions if you are unaware of some other potential culprit.

**Comment by TheChief5055** [comment] 2020-12-25 14:37
Turned AMD Overlay On on Off — no cake. Drivers were not changed between 1.05→1.06 upgrade, no system setting were changed as well.

Crashdump folder available at: [https://dropmefiles.com/ywvRS]

**Closed** 2020-12-27 14:13 UTC

**Comment by lukenYang** [comment] 2020-12-27 14:16
bug fixed in 1.7.1
