### ISSUE TITLE
Crashed after 1-5-10 mins

### ISSUE THREAD

**Issue by map788** [yamashi/CyberEngineTweaks#649] opened 2022-02-16 11:28 UTC
Problem after playing game. using i7-7700k, gtx 1080
crashing after 1-5-10 min

x64 win, r.c for 1.5
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/8079465/cyber_engine_tweaks.log)

**Comment by yamashi** [comment] 2022-02-16 12:08
Note: potential d3d12 memory leak caused by resizing the viewport too many times

**Comment by IffyChan** [comment] 2022-02-21 10:20
@yamashi I think that's how it is. I enabled UseD3D8to9 in global.ini and the crashes stops

**Comment by yamashi** [comment] 2022-02-21 17:29
Wow that's weird, have no idea how this could cause issues but thanks a lot for reporting this, I will try to understand what's going on

**Comment by yamashi** [comment] 2022-06-23 19:01
Likely fixed by newer hooking method

**Closed by yamashi** 2022-06-23 19:01 UTC
