### ISSUE TITLE
[Issue] Possible Resolution Problem for use in Full Screen

### ISSUE THREAD

**Issue by MdosTV** [yamashi/CyberEngineTweaks#329] opened 2020-12-29 20:33 UTC
So I have found on my own that the only way to get the Command Console GUI to function normally in Full Screen and let me select exactly where I am clicking is to make sure that both the game resolution and my monitor resolution are the same (ie. set both to 1920 x 1080).

I am wondering if maybe this is because the selectable fields and the graphical interface are based on different resolutions (one is based on game resolution, the other is based on set monitor resolution)?

Thought I would share this, as this is the only way I have found to get the Command Console to work in Full Screen.

**Comment by WSSDude420** [comment] 2020-12-29 21:29
Well, console in fullscreen seems to be a mess in general.

Problems seems to be they misuse few buffers that we happen to need when they change resolution.
At least I believe this is what is wrong, I think this was discussed somewhere already...

Anyway. console functions in windowed and borderless as expected, we advice against fullscreen.
Even in "How to install" it is stated: https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/installing

Fullscreen is messy due to kind of messy implementation CDPR has and is questionable if it will get better at this point. 
For now, this is proven to work as intended.

**Comment by NielsGx** [comment] 2020-12-29 21:31
@WSSDude420 Exclusive fullscreen is superior in every way, especially when it comes to latency. I don't want to play a first person shooter with latency..

I have no issues with the console command and fullscreen. The only issue is when you have fullscreen+console+skip start menu.
At least for me, 1080p, gtx 1060

**Comment by WSSDude420** [comment] 2020-12-29 21:48
I understand... 

But as I mentioned under your, now closed issue for whatever reason (prolly cause it was kind of duplicate), I don't think this will get fixed soon, if ever.

**Comment by NielsGx** [comment] 2020-12-29 21:56
Yeah I guess it's hard to fix it, especially if you say that CDPR did weird thing in their implementation.
I would prefer it to be disabled by default, but if you think a lot of people play in borderless and don't care to have a bit more latency, do as you like, either way I will change my own ini.

Not sure if ultra low latency mode from nvidia works in borderless also. It's great anyway, I don't even loose framerate on my hard-gpu bottleneck setup, but it seems way more responsive.

**Comment by NielsGx** [comment] 2020-12-29 21:57
Are you sure you have issues with console and fullscreen with the skip start menu disabled ? Maybe that could help you to find the cause of all this.

Or i'm just lucky..

**Comment by WSSDude420** [comment] 2020-12-29 22:07
I actually have zero issues with Fullscreen apart from trying to clickity-click during startup somewhere else so game window loses focus during opening and that freeze happens that you mentioned when trying to give it focus again.

I have enabled console, skip start menu, skip intro, disable async compute (as I have 1070 Ti which does not have it)
I also have same resolution as my monitor, so reading this, seems I found out how it may be working for me while it fails for so many others...

Regarding why that patch minimizes window for you, honestly dunno how that happens... Does not happen to me so cannot reproduce it to test it properly.
It minimizes for me only when I try to launch the game and click on something else in the mean time till game window has time to appear.

So to conclude, i have following config and am able to use fullscreen, apparently thanks to set ingame resolution as my monitor resolution so no resize happens in the middle.

```
{
    "avx": false,
    "console": true,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.5,
    "disable_antialiasing": false,
    "disable_async_compute": true,
    "disable_boundary_teleport": true,
    "disable_intro_movies": true,
    "disable_vignette": false,
    "dump_game_options": false,
    "enable_debug": false,
    "gpu_memory_pool_fraction": 1.0,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": false,
    "virtual_input": false
}
```

**Comment by NielsGx** [comment] 2020-12-29 22:11
I have a GTX 1060 so normally disabling async should help, but I do not see any difference, weird.
It's not really related to this issue tho

So yeah it seems to happend when you have different resolution between the game and windows, or changing mid game, interesting

**Comment by WSSDude420** [comment] 2020-12-30 10:48
We will try to work around it somehow...

We discussed some plans for this on Discord, hopefully we come with something that works better.

**Comment by skeevy420** [comment] 2020-12-30 14:08
I just wanted to add to the discussion that adding `--launcher-skip` to the launch options allows skipping the launcher app which makes CET work a lot better overall; in my case perfectly for going from 4K into 1080p using fullscreen.  There's still the issue of doing background clicks before the game goes fullscreen, but skipping the launcher and having mouse discipline helps a lot.

With that flag I went from not being able to use the console or disable intro movie patches to everything just working.

**Comment by WSSDude420** [comment] 2020-12-30 14:42
Look at #338 

It is almost complete, it will be in next release.
It tries to work around CDPR improper impl and reinitialize on resolution changes, as these are one which are fatal.

**Comment by WSSDude420** [comment] 2020-12-30 17:07
Fix PR was merged, so will be fixed in future release.

**Closed** 2021-01-01 16:00 UTC
