### ISSUE TITLE
Cannot set overlay toggle key

### ISSUE THREAD

**Issue by Senfee-Cheng** [yamashi/CyberEngineTweaks#733] opened 2022-11-09 09:20 UTC
![图片](https://user-images.githubusercontent.com/20067002/200790458-a922aab6-4572-4447-ae07-56f4e23b71dc.png)
There is no mouse cursor here, and the selected button cannot be switched between left and right buttons. I hope that if the mouse is not available, at least you need to use the keyboard to set these.

**Comment by WSSDude420** [comment] 2022-11-09 09:36
I cant reproduce this. It seems to affect some users, cause is unknown... Doesnt seem to relate to Windows version, Steam/GOG/EGS, fullscreen/borderless... Kind of out of ideas what may be the cause...
Something is blocking things for you, cannot tell what...
Try launching Cyberpunk2077.exe directly, without any params etc.
Also, if you have any other mods, would try with just CP77 and CET. There is a possibility of some mod interference we did not detected yet...

**Comment by WSSDude420** [comment] 2022-11-09 09:38
Note that any mods that are not archive mods may potentially be the cause so remove redmods and redscripts if direct launch from exe does not work.

If something helps you from this, good. If not, honestly a mistery for now unless someone manages to find the cause.

**Comment by Senfee-Cheng** [comment] 2022-11-09 09:40
> Note that any mods that are not archive mods may potentially be the cause so remove redmods and redscripts if direct launch from exe does not work.
> 
> If something helps you from this, good. If not, honestly a mistery for now unless someone manages to find the cause.

I don't use any mods, and the game folder is very clean. I'm not sure what blocks the ui, but when I configure a value, it will work. For example,~represents "54043195528445952"

**Comment by WSSDude420** [comment] 2022-11-09 09:41
Yeah that is known that it works if you set it manually. Something is messing with early toggle or how to call it. I cant figure out what :(

**Comment by dNifle** [comment] 2022-11-09 15:06
Had the same issue while running the game via Lutris. I had to click onto the bind button while tabbed out for it to work. I have a fresh installation with only CET and Native Settings UI. Same issue and solution inside the tweaks menu.

**Comment by WSSDude420** [comment] 2022-11-09 20:43
Fixed by https://github.com/yamashi/CyberEngineTweaks/commit/81852491baff76ed2bc731a16e307f468566d3ce
Hotfix should get released soon hopefully.

**Closed by WSSDude420** 2022-11-09 20:43 UTC
Labels: bug, help wanted
