### ISSUE TITLE
Enable Secret Ending

### ISSUE THREAD

**Issue by AB110297** [yamashi/CyberEngineTweaks#234] opened 2020-12-21 22:45 UTC
Do you guys think its possible to enable the secret ending manually using the dev console ? or do you know of any modding efforts to make the secret ending easily available for people who dont want to replay the whole game again just to get that ending ? 

Happy Holidays and thanks for the great work 👍

**Comment by rmarquis** [comment] 2020-12-21 23:16
Duplicate of #225.

**Comment by bad1dea** [comment] 2020-12-21 23:56
I posted a copy and paste from discord with answer.

**Closed** 2020-12-22 00:36 UTC
