### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by yamashi** [yamashi/CyberEngineTweaks#134] opened 2020-12-18 23:05 UTC
Apparently people are still using windows 7 and play directx12 games with a conversion layer...

Currently the overlay hook is based on real directx12, a directx11 hook needs to be developed and used when on windows 7.

I don't plan on implementing it, as it requires installing windows 7 and spending time I don't have on a very small player base.

If you want to give it a shot please do.

**Comment by asdf2345** [comment] 2020-12-18 23:20
This would take an hour to install, and probably another hour to get all the drivers installed, but it won't take that long, and you'll have a better OS in the end.

https://www.reddit.com/r/LegacyWindows/wiki/index/windows-7/windows-7-iso-with-integrated-updates

**Comment by r4m0n** [comment] 2020-12-20 05:29
Maybe a config option to disable the overlay then? Should be a lot easier to implement and still keep the general optimization options.

**Comment by Squall-Leonhart** [comment] 2020-12-20 05:46
> Apparently people are still using windows 7 and play directx12 games with a conversion layer...

12on7 is a complete Dx12 implementation to the equivalent of that included with Windows 10 1809, but limited to the capabilities of DXGI 1.1 where swap chains are concerned.

**Comment by rrrudd** [comment] 2020-12-20 16:15
Please add option to disable overlay like r4m0n suggested.

**Comment by Megalomaniak** [comment] 2020-12-21 01:41
I think the issue is not DX12, people can just copy the dlls from the dx12on7 folder to the above folder with the game exe in it so it will be found, but XInput1_4 is what isn't available on windows 7. Could try using/looking for 1_3 for it I think, not sure if that helps tho.

**Comment by r4m0n** [comment] 2020-12-21 04:26
> I think the issue is not DX12, people can just copy the dlls from the dx12on7 folder to the above folder with the game exe in it so it will be found, but XInput1_4 is what isn't available on windows 7. Could try using/looking for 1_3 for it I think, not sure if that helps tho.

I've tried disabling the xinput option and grabbing a 1.4 xinput DLL. it stops complaining about missing DLLs, but gives a couple errors 193 and doesn't work (game loads normally).

**Comment by puchev** [comment] 2020-12-21 06:21
> I've tried disabling the xinput option and grabbing a 1.4 xinput DLL. it stops complaining about missing DLLs, but gives a couple errors 193 and doesn't work (game loads normally).
Copying both xinput1_3.dll and d3d12on7/d3d12.dll to plugins/ and renaming the former to xinput1_4.dll should allow the plugin to work on 7 (except for the overlay obviously). Or at least it did, I have yet to update to 1.05 and my plugin is like 2 days old.

**Comment by rrrudd** [comment] 2020-12-21 07:51
> 
> 
> > I've tried disabling the xinput option and grabbing a 1.4 xinput DLL. it stops complaining about missing DLLs, but gives a couple errors 193 and doesn't work (game loads normally).
> 
> Copying both xinput1_3.dll and d3d12on7/d3d12.dll to plugins/ and renaming the former to xinput1_4.dll should allow the plugin to work on 7 (except for the overlay obviously). Or at least it did, I have yet to update to 1.05 and my plugin is like 2 days old.

It's working. I don't know if everything is working correctly.

1. Copy d3d12.dll to /plugins
2. Copy xinput1_3.dll to /plugins and rename it to xinput1_4.dll

cyber_engine_tweaks.log says [error] Kiero failed!

3. Set console option to false

Game runs, but in 1024x768 resolution

4. Change resolution in game options, exit and run game again

Resolution is fine now.

This is my config.json

```
{
    "avx": true,
    "console": false,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.75,
    "disable_antialiasing": false,
    "disable_async_compute": true,
    "disable_boundary_teleport": false,
    "disable_intro_movies": true,
    "disable_vignette": false,
    "dump_game_options": false,
    "enable_debug": false,
    "gpu_memory_pool_fraction": 1.0,
    "memory_pool": true,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": true,
    "spectre": true,
    "virtual_input": false
}
```

**Comment by sumyunggai** [comment] 2020-12-24 18:18
Since Win7 is semi-officially not supported, I'll post this here rather than create a new issue.

For CP v1.05, following @rrrudd's advice worked on engine tweaks v161 with the following config.json

> {
>   "avx": true,
>    "console": false,
>    "cpu_memory_pool_fraction": 0.5,
>    "disable_antialiasing": false,
>    "disable_async_compute": true,
>    "dump_game_options": false,
>    "gpu_memory_pool_fraction": 1.0,
>    "memory_pool": true,
>    "remove_pedestrians": false,
>    "skip_start_menu": true,
>    "smt": true,
>    "spectre": true,
>    "unlock_menu": false,
>    "virtual_input": true,
>    "disable_intro_movies": true,
>    "disable_vignette": false,
>    "disable_boundary_teleport": false
> }

And I could run CP without issue,

> [2020-12-23 15:53:40.944] [info] Game version 1.05
> [2020-12-23 15:53:40.984] [info] 	AMD SMT Patch: success
> [2020-12-23 15:53:40.984] [warning] 	Spectre patch: failed, unknown version
> [2020-12-23 15:53:41.004] [warning] 	Virtual Input Patch: failed
> [2020-12-23 15:53:41.064] [info] 	Start screen patch: success
> [2020-12-23 15:53:41.064] [info] 	Hidden options patch: success
> [2020-12-23 15:53:41.074] [info] 	Disable intro movies patch: success

Now, with CP v1.06 and engine tweaks v170, I get 

> Unable to load cyber_engine_tweaks.asi. Error: 998

With no print out to the log. Same configuration as before (i.e. console disabled since I'm using d3d12.dll in the plugins folder on win7 x64).

Any idea?

**Comment by Mattiwatti** [comment] 2020-12-26 13:22
I did some investigating into the cause of the Error 998 that @sumyunggai reported, as I had the same issue. This error is caused by an access violation while `cyber_engine_tweaks.asi` is being loaded, with the following callstack:

![callstack](https://user-images.githubusercontent.com/3313892/103149446-c3f9d380-4769-11eb-90ac-502045df77c5.png)

The `modmul_from_right_fastx64_asm` frame reported by Visual Studio is bogus, this is actually `BCryptGenRandom`. The `_mi_XXX` frames are [Mimalloc](https://github.com/microsoft/mimalloc). Mimalloc is a dependency of [TiltedCore](https://github.com/tiltedphoques/TiltedCore), which in turn is a dependency of Cyber Engine Tweaks. So this is not actually a bug in Cyber Engine Tweaks as far as I can tell. However it should be fairly easy to fix or at least work around.

The main issue seems to be that `BCryptGenRandom` misbehaves on Windows 7 when called from within a `DllMain` function (possibly depending on the parameters passed to it by Mimalloc). Why do I say this? Because this crash does not happen if the ASI loader is compiled as a .exe file instead of as DLL.

Mimalloc actually provides a way to specify at compile time that you do not wish to use `BCryptGenRandom` to initialize the PRNG: see [os_random_buf](https://github.com/microsoft/mimalloc/blob/4cc8bff90d9e081298ca2c1a94024c7ad4a9e478/src/random.c#L166) which is implemented differently depending on an #if guard. Defining `MI_USE_RTLGENRANDOM` will cause it to use `RtlGenRandom` to initialize the PRNG instead. Unfortunately I don't have enough knowledge of xmake to specify that I want to pass this define to a package dependency (not a build target) and then build this dependency from source, if this is even possible.

As a workaround until this is fixed properly somewhere in the above mentioned dependency chain, I simply added the TiltedCore source files to the makefile, sans the Mimalloc-related source files. This also required changing one instance of `MimallocAllocator` in `src/Allocator.cpp` to the basic `malloc`-using `StandardAllocator`. After this, Cyber Engine Tweaks once again works on Windows 7 using Cyberpunk v1.06 and the current git tree at dd2b5d8:
> [2020-12-26 10:40:50.916] [info] Game version 1.06
[2020-12-26 10:40:51.069] [info] 	AMD SMT Patch: success
[2020-12-26 10:40:51.132] [info] 	Start screen patch: success
[2020-12-26 10:40:51.134] [info] 	Hidden options patch: success
[2020-12-26 10:40:51.137] [info] 	Disable intro movies patch: success
[2020-12-26 10:40:51.215] [info] 	Hidden options hook: success
[2020-12-26 10:40:51.233] [info] 	Hook mouse clip function!
[2020-12-26 10:40:51.240] [info] 	Log function hook complete!
[2020-12-26 10:40:51.249] [info] 	LogChannel function hook complete!
[2020-12-26 10:40:51.324] [info] 	TDBID::ctor function hook complete!
[2020-12-26 10:40:51.400] [info] 	TDBID::ctor[CString] function hook complete!
[2020-12-26 10:40:51.475] [info] 	TDBID::ctor[Derive] function hook complete!
[2020-12-26 10:40:51.551] [info] 	TDBID::ctor[Unknown] function hook complete!
[2020-12-26 10:40:51.575] [info] 	TDBID::ToStringDEBUG function hook complete!

The 'function hook complete' messages are due to me having the console enabled, but keep in mind that the console still does not actually work on Windows 7 due to the D3D12 issues already mentioned in this thread.

**Comment by Mattiwatti** [comment] 2020-12-26 13:24
(Continued from my previous post as it was getting long, and this comment is unrelated to the error 998 message.)

While @rrrudd's advice is very good in that it will get Cyber Engine Tweaks to work on Windows 7 the way it is right now, I have some objections to using this approach in the long run that are related to global state in DLLs. Duplicating `d3d12.dll` and `xinput_1_3.dll` means that the DirectX interfaces responsible for graphics and input will be loaded twice in the same process; one for Cyberpunk and one for Cyber Engine Tweaks. These DLLs will not be aware of each other's existence, which can be an issue in any place where global state is used by the DLL to store data, since this state will most likely differ between the two DLLs.

(Note that Cyber Engine Tweaks incorrectly linking against `xinput_1_4.dll` causes this to happen even on Windows 10, so this is not a problem exclusive to Windows 7. However, duplicating `d3d12.dll` in a process is probably a more serious problem that is exclusive to Windows 7.)

I found a way to load the correct DLL (meaning the same DLL that the game is using) for both:
- `xinput_1_3.dll`: I modified `src/overlay/imgui_iml_win32.cpp` to link against the import library for `xinput_1_3.dll` instead of the `xinput_1_4.dll` it is currently linking against due to the import library coming from the Windows SDK. An issue here is that this import library is only available as part of the [June 2010 DirectX SDK](https://www.microsoft.com/en-us/download/details.aspx?id=6812) which most people won't have installed. Adding it to the Github repository could be an option since it is only 3 KB, but I don't know if it is permitted by the EULA to redistribute SDK files separately.
- `d3d12.dll`: this file is very inconveniently placed in `/d3d12on7` in the Cyberpunk directory. I don't know why CDPR decided to give it its own subdirectory given that it is very simple to load this DLL from the game directory on Windows 7 and from System32 on Windows 10. This issue can be resolved in two ways: (1) making [Ultimate ASI Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader) add `/d3d12on7` to its DLL search path, or (2) making Cyber Engine Tweaks load `d3d12.dll` dynamically instead of statically, since it is aware of its own location and that of Cyberpunk's `d3d12.dll`. I tested (1) as it was the quickest to implement and this works, but ultimately I think (2) is the way this should be handled. I will make a PR for this soon assuming I can get it to work correctly without breaking things on Windows 10.

**Comment by Mattiwatti** [comment] 2020-12-26 13:26
(Last comment from me for now, I promise! This one is about supporting D3D12 on Windows 7.)

I'm not a graphics programmer so unfortunately I doubt I can just make a PR that makes all the necessary changes for this, but I do have some notes that may be of interest to @yamashi or anyone else looking to add support for Windows 7 to the D3D12 overlay.

First of all, D3D12On7 is an official MS project that has some very good documentation and sample code available:
- [Porting D3D12 games to Windows 7 – Development Guidance](https://microsoft.github.io/DirectX-Specs/d3d/D3D12onWin7.html) - documentation;
- [D3D12On7 NuGet package](https://www.nuget.org/packages/Microsoft.Direct3D.D3D12On7) to obtain the headers and latest DLL;
- [D3D12On7 sample](https://github.com/microsoft/DirectX-Graphics-Samples/tree/develop/Samples/Desktop/D3D12On7) - a bit heavy on COM usage and reliance on the d3dx12.h 'helper header' for my taste, but readable enough.

The main issue I can see w.r.t. Windows 7 compatibility in Cyber Engine Tweaks is the use of the DXGI swap chain. This is normally obtained by calling `IDXGIFactory::CreateSwapChain` (this is also what Kiero does to find the address of the command queue pointer relative to the swap chain), but this function is not supported by DXGI on Windows 7.

This means that currently Kiero fails to initialize as the swap chain creation call fails. But this is not extremely important since the only reason Kiero is creating a swap chain is to find the command queue address I mentioned. This goes into `g_commandQueueOffset` which is later used by the overlay. Other function pointers from the D3D12 device, command queue, command allocator, command list and swapchain itself go in `g_methodsTable`, but these are not actually used by the overlay later.

These are the main problematic functions in the overlay due to their usage of the swap chain:
- `Overlay::PresentD3D12(IDXGISwapChain3* pSwapChain, UINT SyncInterval, UINT Flags)`
- `Overlay::InitializeD3D12(IDXGISwapChain3* pSwapChain)`
- `Overlay::Render(IDXGISwapChain3* pSwapChain)`

`Overlay::PresentD3D12` is the hook for the DXGI present function. The location of this hook will have to be moved on Windows 7, as Cyberpunk will not (can not) call a function with this signature due to absence of a swap chain. Instead the `ID3D12CommandQueueDownlevel` interface is used to call a present function with the following signature:
```C++
HRESULT STDMETHODCALLTYPE Present( 
    _In_  ID3D12GraphicsCommandList *pOpenCommandList,
    _In_  ID3D12Resource *pSourceTex2D,
    _In_  HWND hWindow,
    D3D12_DOWNLEVEL_PRESENT_FLAGS Flags);
```
The `ID3D12CommandQueueDownlevel` can be obtained from the command queue using `QueryInterface`.

`Overlay::InitializeD3D12` is called once by the Present hook. This looks to be me to be the trickiest function to adapt for Windows 7. Firstly it uses the swap chain to obtain the D3D12 device pointer. On Windows 7 this can be achieved by querying the device from the back buffer resource that is created instead of a swap chain (see [here](https://github.com/microsoft/DirectX-Graphics-Samples/blob/2fcd597aa45b3dc4c95bfbc0c4f4a79948864019/Samples/Desktop/D3D12On7/src/D3D12On7.cpp#L121)), but that still implies finding the back buffer resource somehow (pattern matching, or otherwise disassembly of the game binary to find where it stores the result of this call). Next, the swap chain is used to obtain the `DXGI_SWAP_CHAIN_DESC` that was used to create it, in order to determine the size of the `FrameContext` vector (size = `sdesc.BufferCount`). There is no clear equivalent obtainable on 7 that I can see, but note that the MS sample treats this value as a constant `2`, so it may not be overly important. Finally, the swap chain is used to obtain the address of the command queue (`m_pCommandQueue`). This address could be obtained alternatively in the hook for `ID3D12CommandQueueDownlevel::Present()` mentioned previously, since the first parameter to this function is the command list which can be used to obtain the command queue.

`Overlay::Render()` should be simple. It only uses the swap chain to obtain the current back buffer index. In the MS sample the back buffer index is simply initialized to 0, and **if** a swap chain is available (i.e. on Windows 10), this swap chain is used to obtain a potentially different index.

**Comment by waruqi** [comment] 2020-12-26 15:56
> Mimalloc actually provides a way to specify at compile time that you do not wish to use BCryptGenRandom to initialize the PRNG: see os_random_buf which is implemented differently depending on an #if guard. Defining MI_USE_RTLGENRANDOM will cause it to use RtlGenRandom to initialize the PRNG instead. Unfortunately I don't have enough knowledge of xmake to specify that I want to pass this define to a package dependency (not a build target) and then build this dependency from source, if this is even possible.

@Mattiwatti try `add_requires("mimalloc", {configs = {cxflags = "-DMI_USE_RTLGENRANDOM"}})` or you can submit a pr to add a config item ("rtlgen_random") in xmake-repo/mimalloc, then use `add_requires("mimalloc", {configs = {rtlgen_random = true})`

like this https://github.com/xmake-io/xmake-repo/blob/78687acd47e2b63ab21c640d436d554fb021d8fd/packages/m/mimalloc/xmake.lua#L10

**Comment by yamashi** [comment] 2020-12-26 18:19
> 
> 
> > Mimalloc actually provides a way to specify at compile time that you do not wish to use BCryptGenRandom to initialize the PRNG: see os_random_buf which is implemented differently depending on an #if guard. Defining MI_USE_RTLGENRANDOM will cause it to use RtlGenRandom to initialize the PRNG instead. Unfortunately I don't have enough knowledge of xmake to specify that I want to pass this define to a package dependency (not a build target) and then build this dependency from source, if this is even possible.
> 
> @Mattiwatti try `add_requires("mimalloc", {configs = {cxflags = "-DMI_USE_RTLGENRANDOM"}})` or you can submit a pr to add a config item ("rtlgen_random") in xmake-repo/mimalloc, then use `add_requires("mimalloc", {configs = {rtlgen_random = true})`
> 
> like this https://github.com/xmake-io/xmake-repo/blob/78687acd47e2b63ab21c640d436d554fb021d8fd/packages/m/mimalloc/xmake.lua#L10

Don't think that would work, it's not a cmake parameter, it's just a define that needs to be set, I suppose we can add a patch to the mimalloc package.

**Comment by Mattiwatti** [comment] 2020-12-26 20:06
Actually `add_requires("mimalloc", {configs = {cxflags = "-DMI_USE_RTLGENRANDOM"}})` works for me and fixes the access violation on Windows 7, as the bcrypt PRNG initialization is now gone. Still need to test this on Windows 10 but I assume it will work.

**Comment by sumyunggai** [comment] 2020-12-28 18:34
@Mattiwatti did v172 resolve your 998 error? It did not for me (console still disabled).

FYI to @yamashi: there's duplicate copies of "cyber_engine_tweaks.asi" in the v172 release .zip - one in root with the other in \plugins

**Comment by GreenyX1** [comment] 2020-12-29 02:02
Same here, 998 error 
But it's no longer asking for xinput1_4

**Comment by Legoras** [comment] 2020-12-29 17:30
Yes, error 998.

**Comment by Mattiwatti** [comment] 2020-12-29 20:50
@sumyunggai and others: there is some confusion re: what changes are required for Windows 7 support to work, so let me list them for clarification:
- Remove `d3d12.dll` static import: done in #301 (merged), in release 1.7.2+.
- Remove `XInput_1_4.dll` static import: done in #305 (merged), in release 1.7.2+.
- (Fixes error 998) Remove `bcrypt.dll` static import and dependency, done in #303 (not merged), not in any release yet.
- Add support for the console overlay to Windows 7, done in #318 (merged), not in any release yet.

So the error 998 and console overlay fixes are in different changes, and neither are (currently) in any release yet.

The console overlay support merge should hopefully be in the next release. Although this isn't useful without the error 998 fix, since that is needed for the mod to work in the first place.

Error 998 was fixed in a different method than the one proposed in my PR (namely a change in xmake to support requiring `mimalloc` with an alternative RNG source - see the PR for details). But this change is not in the source code yet. @yamashi will probably be able to say if/when this will get merged, as it probably requires contributors to have a new version of xmake installed.

**Comment by waruqi** [comment] 2020-12-30 02:45
> But this change is not in the source code yet. @yamashi will probably be able to say if/when this will get merged, as it probably requires contributors to have a new version of xmake installed.

I don’t think we need not upgrade the xmake version, just execute `xmake repo -u` to update the xmake-repo repository, and then reinstall the mimalloc dependency package.

because I have fixed titledcore package in xmake-repo and enabled rltgenrandom config to mimalloc deps. (https://github.com/xmake-io/xmake-repo/blob/614cd5d8bca139ab019632a8b6350aa47f3bf7e9/packages/t/tiltedcore/xmake.lua#L12)

```console
cd CyberEngineTweaks
xmake repo -u
xmake require --uninstall mimalloc # or delete %localappdata%/.xmake/packages/m/mimalloc
xmake f -c # reinstall mimalloc
xmake
```

**Comment by 3xploitch3ats** [comment] 2020-12-30 02:56
this is not for be bad
so i make the 
# https://thunder-menu.com 
since 3 years
and it think if you want your mod it will be compatible with 
the support of windows 7 that will end the 14 january
you only need to compiled it with the version of windows sdk 8.1

**Comment by GreenyX1** [comment] 2021-01-02 04:28
v1.8.0 no more errors. Console crashes to desktop but other functionality seems to work.

**Comment by Mattiwatti** [comment] 2021-01-02 22:12
Unfortunately v1.8.0 was released right after a change to the console overlay size that the Windows 7 code didn't make it in time for, and additionally there is window resize detection implemented in this version which works on my system but causes a crash to desktop on others.

I've created #358 to fix these issues; if this is merged it should make the next release. Meanwhile if you're eager to get the console on Windows 7, you can already download the build artifact for the PR [here](https://github.com/yamashi/CyberEngineTweaks/suites/1756369368/artifacts/33425878).

**Closed** 2021-01-02 22:49 UTC
Labels: enhancement, help wanted

**Comment by sumyunggai** [comment] 2021-01-02 23:20
Thanks to everyone for getting win7 support functional!
