### ISSUE TITLE
If MSI AFTERBURNER is turned on before the game is executed, the Console cannot be called.

### ISSUE THREAD

**Issue by Inory0203** [yamashi/CyberEngineTweaks#286] opened 2020-12-25 09:10 UTC
If MSI AFTERBURNER is turned on before the game is executed, the Console cannot cannot be called.

**Comment by hadewych** [comment] 2020-12-25 09:11
I dont have this issue I tried to reproduce it, Can you be more specific?

**Comment by WSSDude420** [comment] 2020-12-25 09:27
Known issue, it is caused by RivaTuner Statistics Server.

#285 

Owner doesnt want to fix it... It worked in previous versions, it seems he fixed Reshade from what he said there, but he ultimately broke this to all hell, cannot get it to work now at all...

And he doesnt seem to want to revert it back :)
Even though it starts to get polluted here with people withr RTSS...

Have fun guys :)

**Comment by Inory0203** [comment] 2020-12-25 09:32
Oh, I have RTSS installed, so can I only turn on RTSS after the game is running?

**Comment by WSSDude420** [comment] 2020-12-25 09:36
Yes, but as you probably have it installed with Afterburner as I have it, you basically have to shut down whole Afterburner and then RTSS, as if you shut down just RTSS, Afterburner starts it right back for me...

So just extra hussle on extra hussle...

But yes, that is something you can do, sure. Just dont launch RTSS sooner than you get into menu (pro tip :) )

**Comment by Inory0203** [comment] 2020-12-25 09:39
Thank you. :+1:

**Comment by WSSDude420** [comment] 2020-12-25 09:41
If you look inside that pull request I linked, there should be working artifact version (just the .asi file, but that is all that is needed for this anyway, you can get other data from regular release)

With that version from my pull request, you should not need to do this. Only thing you should do is one tweak in RTSS Global profile, which is linked there (comment on other issue).

**Comment by WSSDude420** [comment] 2020-12-25 09:45
Here is link to it if you do now want to search for it...

https://github.com/yamashi/CyberEngineTweaks/suites/1723702700/artifacts/32612438

Under Checks tab in that pull request, there is Artifacts button. This is the link under it.

**Comment by WSSDude420** [comment] 2020-12-25 11:49
Should be fixed to an extent with upcoming release now.

Note though that you should follow this comment for RTSS to work reliably (otherwise, console works half the time and other half is not rendering, depending on which hook was faster...)
https://github.com/yamashi/CyberEngineTweaks/issues/245#issuecomment-750009640

Working on revising whole DX12 hooking procedure now, so hopefully, we will have some more robust solution in place SOON™ which would not require similar stunts from user.

**Closed** 2021-01-01 20:35 UTC
