### ISSUE TITLE
CET prevents all controller input. Uninstalling CET allows for controller input.

### ISSUE THREAD

**Issue by avafromdiscord** [yamashi/CyberEngineTweaks#729] opened 2022-10-22 15:30 UTC
Whenever I install Cyber Engine Tweaks, cyberpunk stops accepting my controller's inputs. Whenever I uninstall CET, the controller functions normally.
Speaking to Mr. Bohemia in Discord, it seems that this is not intentional, and that controller inputs are only meant to be blocked when the overlay is active, and the rest should get passed through.

I'm _**not**_ looking to bind things to the controller, only use it for general gameplay & driving.

My game version is **1.6**
CET is **1.20**
Controller is 8bitdo pro 2 [wired in xinput mode, binds assigned through steam.]

Here is my log file, in case that's of any help.
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/9844705/cyber_engine_tweaks.log)

**Comment by avafromdiscord** [comment] 2022-10-22 18:00
After a bit of digging, I've found that the issue is the steam controller layer.

Here's how I fixed it:

1. Close Cyberpunk
2. Open Big Picture
3. Select Library
4. Select Cyberpunk
5. In the left-hand column, to go Manage Game
6. Select Controller Options
7. Under the *Steam Input Per-Game Setting*, set to Forced Off
8. Launch Cyberpunk

**Comment by WSSDude420** [comment] 2022-11-06 17:16
I cannot replicate this and it seems like it may have been caused by some misconfiguration in Steam so closing this issue for now.

In case someone else stumbles upon this, make sure to look into Steam controller settings for the game, it is possible you have broken layout in some way.

**Closed by WSSDude420** 2022-11-06 17:16 UTC
Labels: bug
