### ISSUE TITLE
1.05 issues

### ISSUE THREAD

**Issue by seccentral** [yamashi/CyberEngineTweaks#155] opened 2020-12-20 00:33 UTC
Patch states they consulted with amd and decided to enable the smt for 4-6 core cpus only as they deemed it sufficient. 
However!
I have an 8-core 2700X and there was a consistent ~10fps difference between smt on and off. Many others report on their forums that 3700/3800Xs also benefit from the SMT patch, regardles of what CDPR thinks is "sufficient". 
Now i created a special save in a crowded city area just for testing this out and here are my results:
1.04 smt true: 82FPS
1.04 smt false: 69-71 FPS
1.05 - AMD SMT Patch: failed : 69-71 FPS
Clearly they don't know what they're talking about and others complain too and this feature should stay ON. Can you re-enable it ?

Running mod 1.1.0

Mod log: 
```
[2020-12-20 02:25:54.894] [info] Computed .text crc: 20F87F01
[2020-12-20 02:25:54.894] [error]       Unknown version, please update the mod
[2020-12-20 02:25:54.919] [warning]     AMD SMT Patch: failed
[2020-12-20 02:25:54.919] [warning]     Spectre patch: failed, unknown version
[2020-12-20 02:25:54.920] [info]        AVX Patch: skip, cpu has AVX support
[2020-12-20 02:25:54.992] [info]        Pool patch: failed
[2020-12-20 02:25:55.017] [warning]     Virtual Input Patch: failed
[2020-12-20 02:25:55.077] [info]        Start screen patch: success
[2020-12-20 02:25:55.116] [info]        Hook mouse clip function!
[2020-12-20 02:25:55.405] [info]        D3D12 hook complete
```

**Comment by NielsGx** [comment] 2020-12-20 00:36
Same for me, 3700x. If you could enable the smt thing for 8cores and more, would be great.
Why wouldn't we use async anyway ?

I just don't have the last 2 lines in my log

**Comment by JLBP** [comment] 2020-12-20 00:45
Currently unable to use a controller, nor are the patches working outside of the start screen. Attached is the log

```
cyber_engine_tweaks.log
-------------------------------------------------------------------------------------------
[2020-12-20 00:41:23.816] [info] Computed .text crc: 20F87F01
[2020-12-20 00:41:23.817] [info] 	Resolved to version: 1.05
[2020-12-20 00:41:23.842] [warning] 	AMD SMT Patch: failed
[2020-12-20 00:41:23.842] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 00:41:23.842] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 00:41:23.898] [info] 	Pool patch: failed
[2020-12-20 00:41:23.911] [warning] 	Virtual Input Patch: failed
[2020-12-20 00:41:23.958] [info] 	Start screen patch: success
[2020-12-20 00:41:24.080] [info] 	Hook mouse clip function!
[2020-12-20 00:41:24.183] [info] 	Log function hook complete!
[2020-12-20 00:41:24.549] [info] 	D3D12 hook complete
```

**Comment by Bond198** [comment] 2020-12-20 00:46
Same issue here. 3700x.   AMD SMT Patch: failed

**Comment by NielsGx** [comment] 2020-12-20 00:50
My PS4 controller is working fine as dinput.
Didn't try with ds4windows, or anything that use steam thing

**Comment by JLBP** [comment] 2020-12-20 00:56
> My PS4 controller is working fine as dinput.
> Didn't try with ds4windows, or anything that use steam thing

Can confirm closing steam and running dinput does work fine with a DualShock 4. But using a DualSense did work for me via steam but not dinput

**Comment by brdtoledo** [comment] 2020-12-20 01:07
Same here. I have an 8-core 3700X and now some times FPS drops bellow 50. Before the 1.05 patch with this plugin it was always above 70.

**Comment by yamashi** [comment] 2020-12-20 01:11
Will fix the smt stuff tomorrow I am off to bed!

**Comment by Nicholas-Steel** [comment] 2020-12-20 03:32
Curious, what was the purpose behind artificially limiting SMT access? if it's to maximize energy efficiency on what are assumed to be more than capable pieces of hardware (only reason I can think of for limiting it), maybe make it a toggleable option in the game settings instead of hardcoding the limitation?

**Comment by Shatteredhelix42** [comment] 2020-12-20 04:16
I too got a performance increase with SMT on, I'm using a Ryzen 9 3900x which has 12 cores, 24 threads and was getting an easy 15 FPS increase. My other stats are 32gb DDR4 3200 RAM, and a GTX 1650 GPU (Upgrading to a 3800 or 3800 Ti if they ever become available again) My frames jumped up an easy 10-15 FPS, going from 35 in crowded areas to 45-50, so there is nothing that AMD or CDPR can say to me that will make me believe that SMT doesn't do ANYTHING for CPUs that have over 6 cores. I call SHENANEGANS!

**Comment by Maxz85** [comment] 2020-12-20 05:38
Same here, was running game way more stable on my Ryzen 2600 before the patch, using version 1.1.1 which supposed to be compatible with 1.05 patch.
Here's the .log file it gives me:

> [2020-12-20 08:30:35.616] [info] Computed .text crc: 20F87F01
[2020-12-20 08:30:35.616] [info] 	Resolved to version: 1.05
[2020-12-20 08:30:35.649] [warning] 	AMD SMT Patch: failed
[2020-12-20 08:30:35.649] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 08:30:35.649] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 08:30:35.717] [info] 	Pool patch: failed
[2020-12-20 08:30:35.732] [warning] 	Virtual Input Patch: failed
[2020-12-20 08:30:35.791] [info] 	Start screen patch: success
[2020-12-20 08:30:35.832] [info] 	Hook mouse clip function!
[2020-12-20 08:30:35.862] [info] 	Log function hook complete!
[2020-12-20 08:30:36.040] [info] 	D3D12 hook complete

**Comment by hulovexu1314** [comment] 2020-12-20 09:46
CPU Ryzen 1600x  
using version 1.1.1
[2020-12-20 14:38:05.256] [info] Computed .text crc: 20F87F01
[2020-12-20 14:38:05.256] [info] 	Resolved to version: 1.05
[2020-12-20 14:38:05.288] [warning] 	AMD SMT Patch: failed
[2020-12-20 14:38:05.288] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 14:38:05.288] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 14:38:05.351] [info] 	Pool patch: failed
[2020-12-20 14:38:05.365] [warning] 	Virtual Input Patch: failed
[2020-12-20 14:38:05.419] [info] 	Start screen patch: success
[2020-12-20 14:38:05.420] [info] 	Hidden options patch: success
[2020-12-20 14:38:05.448] [info] 	Hook mouse clip function!
[2020-12-20 14:38:05.468] [info] 	Log function hook complete!
[2020-12-20 14:38:05.702] [info] 	D3D12 hook complete

**Comment by gCioce** [comment] 2020-12-20 11:19
Same here
Ryzen 1600, using 1.1.1

[2020-12-20 12:07:03.969] [info] Computed .text crc: 20F87F01
[2020-12-20 12:07:03.969] [info] 	Resolved to version: 1.05
[2020-12-20 12:07:04.001] [warning] 	AMD SMT Patch: failed
[2020-12-20 12:07:04.001] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 12:07:04.001] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 12:07:04.079] [info] 	Pool patch: failed
[2020-12-20 12:07:04.095] [warning] 	Virtual Input Patch: failed
[2020-12-20 12:07:04.154] [info] 	Start screen patch: success
[2020-12-20 12:07:04.155] [info] 	Hidden options patch: success
[2020-12-20 12:07:04.198] [info] 	Hook mouse clip function!
[2020-12-20 12:07:04.229] [info] 	Log function hook complete!
[2020-12-20 12:07:04.570] [info] 	D3D12 hook complete

**Comment by Hawke677** [comment] 2020-12-20 12:26
Ryzen 1800x
gtx 1080ti
32gb 3200 RAM
version 1.1.1

> [2020-12-20 11:35:21.052] [info] Computed .text crc: 20F87F01
[2020-12-20 11:35:21.052] [info] 	Resolved to version: 1.05
[2020-12-20 11:35:21.077] [warning] 	AMD SMT Patch: failed
[2020-12-20 11:35:21.077] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 11:35:21.077] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 11:35:21.140] [info] 	Pool patch: failed
[2020-12-20 11:35:21.153] [warning] 	Virtual Input Patch: failed
[2020-12-20 11:35:21.206] [info] 	Start screen patch: success
[2020-12-20 11:35:21.207] [info] 	Hidden options patch: success
[2020-12-20 11:35:21.240] [info] 	Hook mouse clip function!
[2020-12-20 11:35:21.264] [info] 	Log function hook complete!
[2020-12-20 11:35:21.631] [info] 	D3D12 hook complete

**Comment by iywang123** [comment] 2020-12-20 12:28
Ryzen 3600, using 1.1.1

[2020-12-20 17:37:24.600] [info] Computed .text crc: 20F87F01
[2020-12-20 17:37:24.601] [info] 	Resolved to version: 1.05
[2020-12-20 17:37:24.624] [warning] 	AMD SMT Patch: failed
[2020-12-20 17:37:24.624] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 17:37:24.624] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 17:37:24.678] [info] 	Pool patch: failed
[2020-12-20 17:37:24.690] [warning] 	Virtual Input Patch: failed
[2020-12-20 17:37:24.734] [info] 	Start screen patch: success
[2020-12-20 17:37:24.764] [info] 	Hook mouse clip function!
[2020-12-20 17:37:24.785] [info] 	Log function hook complete!
[2020-12-20 17:37:25.079] [info] 	D3D12 hook complete

**Comment by ipoopedmypantsuups** [comment] 2020-12-20 12:51
Instructions unclear, car got stuck on roof 🤔 
![image](https://user-images.githubusercontent.com/73392805/102713680-01f18600-4298-11eb-9431-7d262f49ead6.png)

[2020-12-20 07:48:01.496] [info] Game version 1.5
[2020-12-20 07:48:01.543] [info] 	AMD SMT Patch: success
[2020-12-20 07:48:01.543] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 07:48:01.570] [warning] 	Virtual Input Patch: failed
[2020-12-20 07:48:01.629] [info] 	Start screen patch: success
[2020-12-20 07:48:01.673] [info] 	Hook mouse clip function!
[2020-12-20 07:48:01.706] [info] 	Log function hook complete!
[2020-12-20 07:48:01.950] [info] 	D3D12 hook complete

**Comment by callmenemo491** [comment] 2020-12-20 14:55
Using 1.3.0 tool.

[2020-12-20 23:46:39.207] [info] Game version 1.5
[2020-12-20 23:46:39.242] [info] 	AMD SMT Patch: success
[2020-12-20 23:46:39.242] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 23:46:39.255] [warning] 	Virtual Input Patch: failed
[2020-12-20 23:46:39.299] [info] 	Start screen patch: success
[2020-12-20 23:46:39.302] [info] 	Disable intro movies patch: success

Comments:
* game version says 1.5  ... should be 1.0.5
* Spectre patch indicates fail.  -- if not applicable to 1.0.5, could you put in the code to disable it - even if i have it enabled.
* Virtual Input Patch fail.  -- if not applicable to 1.0.5, could you put in the code to disable it - even if i have it enabled.
* log printout should indicate the version of the tool (i.e., 1.3.0)

**Comment by BVZZ** [comment] 2020-12-20 14:59
[2020-12-20 02:29:00.674] [info] Computed .text crc: 20F87F01
[2020-12-20 02:29:00.674] [info] 	Resolved to version: 1.05
[2020-12-20 02:29:00.697] [warning] 	AMD SMT Patch: failed
[2020-12-20 02:29:00.698] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 02:29:00.698] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-20 02:29:00.750] [info] 	Pool patch: failed
[2020-12-20 02:29:00.763] [warning] 	Virtual Input Patch: failed
[2020-12-20 02:29:00.806] [info] 	Start screen patch: success
[2020-12-20 02:29:00.833] [info] 	Hook mouse clip function!
[2020-12-20 02:29:00.852] [info] 	Log function hook complete!
[2020-12-20 02:29:01.205] [info] 	D3D12 hook complete

SMT patching failing on Ryzen 3700X. Using v1.3.0 release

**Comment by yamashi** [comment] 2020-12-20 15:13
Doesnt look like 1.3.0... there is no crc anymore..

**Comment by BVZZ** [comment] 2020-12-20 16:33
> Doesnt look like 1.3.0... there is no crc anymore..

Did a clean install of the release, instead of overwrite, and now it's succeeding. Thanks.

[2020-12-20 16:31:50.533] [info] Game version 1.5
[2020-12-20 16:31:50.568] [info] 	AMD SMT Patch: success
[2020-12-20 16:31:50.568] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 16:31:50.581] [warning] 	Virtual Input Patch: failed
[2020-12-20 16:31:50.625] [info] 	Start screen patch: success
[2020-12-20 16:31:50.628] [info] 	Disable intro movies patch: success
[2020-12-20 16:31:50.653] [info] 	Hook mouse clip function!
[2020-12-20 16:31:50.672] [info] 	Log function hook complete!
[2020-12-20 16:31:50.943] [info] 	D3D12 hook complete

**Comment by IrvinDgl** [comment] 2020-12-20 18:03
tried uninstall and install but still not working 

[2020-12-20 18:52:44.564] [info] Game version 1.5
[2020-12-20 18:52:44.608] [warning] 	AMD SMT Patch: failed
[2020-12-20 18:52:44.608] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 18:52:44.621] [warning] 	Virtual Input Patch: failed
[2020-12-20 18:52:44.670] [info] 	Start screen patch: success
[2020-12-20 18:52:44.674] [info] 	Disable intro movies patch: success
[2020-12-20 18:52:44.698] [info] 	Hook mouse clip function!
[2020-12-20 18:52:44.714] [info] 	Log function hook complete!
[2020-12-20 18:52:44.938] [info] 	D3D12 hook complete
[2020-12-20 18:56:07.422] [info] Game version 1.5
[2020-12-20 18:56:07.485] [warning] 	AMD SMT Patch: failed
[2020-12-20 18:56:07.485] [warning] 	Spectre patch: failed, unknown version
[2020-12-20 18:56:07.498] [warning] 	Virtual Input Patch: failed
[2020-12-20 18:56:07.547] [info] 	Start screen patch: success
[2020-12-20 18:56:07.550] [info] 	Disable intro movies patch: success
[2020-12-20 18:56:07.580] [info] 	Hook mouse clip function!
[2020-12-20 18:56:07.601] [info] 	Log function hook complete!
[2020-12-20 18:56:07.851] [info] 	D3D12 hook complete

**Comment by shelterx** [comment] 2020-12-20 23:29
Spectre patch fails on 1.05 for some reason, the rest seems to work.
Unknown version.

Also, shouldn't game version be 1.05 and not 1.5 in the log.

**Comment by vgf89** [comment] 2020-12-21 05:00
Steam Controller doesn't work with the mode enabled on my GOG copy. Without the mod it's fine.
https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/165

**Comment by ArturVRSampaio** [comment] 2020-12-21 12:07
before say that the game runs better or worst, please watch the gamersnexus video about the 1.05 update...
https://www.youtube.com/watch?v=G5jTaa4Wj7Y

as he calls, the game is really, really unstable, so maybe the performance enhance, or downgrade can be nothing more than the game itself being unpolished

**Comment by ChinZer0** [comment] 2020-12-21 16:38
why Spectre patch fails? 
I'm sorry for asking, I'm sure many of us have the same problem, we just want to be aware that the developer of this tool is solving it, thank you very much

**Comment by FIying-Scotsman** [comment] 2020-12-21 18:30
> why Spectre patch fails?
> I'm sorry for asking, I'm sure many of us have the same problem, we just want to be aware that the developer of this tool is solving it, thank you very much

It fails because the memory pattern it looks for has changed due to the update. The new memory pattern has to be found before the patch can be re-applied properly.

**Comment by WaschBaer0395** [comment] 2020-12-22 17:52
> before say that the game runs better or worst, please watch the gamersnexus video about the 1.05 update...
> https://www.youtube.com/watch?v=G5jTaa4Wj7Y
> 
> as he calls, the game is really, really unstable, so maybe the performance enhance, or downgrade can be nothing more than the game itself being unpolished

gamersnexus can say what he want, the fact that people notice a difference immediately tells us hes wrong, also he tested it all using a 3080 or 3090 something that not even everyone has access to. on my 3700x it made a difference a noticeable difference in frame stability , everytime thats not a thing  that is caused by the game being unstable in general, not when it only happens after YOU change something that others already said is making a difference   
the memory pools thing i also dont understand , its not a restart that made it better it cant be since i was able to notice a drop in frames 20mins into gameplay consistently everytime i removed the memory pools patch, and with it installed i was able to play for hours without a general drop in frames

**Comment by ArturVRSampaio** [comment] 2020-12-22 18:31
> > before say that the game runs better or worst, please watch the gamersnexus video about the 1.05 update...
> > https://www.youtube.com/watch?v=G5jTaa4Wj7Y
> > as he calls, the game is really, really unstable, so maybe the performance enhance, or downgrade can be nothing more than the game itself being unpolished
> 
> gamersnexus can say what he want, the fact that people notice a difference immediately tells us hes wrong, also he tested it all using a 3080 or 3090 something that not even everyone has access to. on my 3700x it made a difference a noticeable difference in frame stability , everytime thats not a thing that is caused by the game being unstable in general, not when it only happens after YOU change something that others already said is making a difference
> the memory pools thing i also dont understand , its not a restart that made it better it cant be since i was able to notice a drop in frames 20mins into gameplay consistently everytime i removed the memory pools patch, and with it installed i was able to play for hours without a general drop in frames


I'm sorry if i made myself not understandably, lets try again ok?
i recommend anyone who wants to claim if anything made the game better or worst, make a lot of tests, because as said by gamersnexus, the game is unstable and the frame time can change a lot from restart to restart. And about any CPU patchs, its important to remember that most of the time the game is GPU bounded, so any patches for the CPU will only affect when your CPU is/was the bottleneck (that's why the 3080 or 3090 for the tests ;) ) 

I'm not telling anyone the patches don't work or anything like that, i'm just explaining that, not every time the game runs more or less smoothly it's because of the patches. the game is **REALLY** unstable in frame times as said in the video i linked up :)

sorry about my bad eng... not my first lang

**Comment by Benman2785** [comment] 2020-12-23 14:09
hex codes for v1.05

"75 2D 33 C9 B8 01 00 00 00 0F A2 8B C8 C1 F9 08"

change "75" to "74" for AMD or "EB" for Intel (and AMD)

**Comment by l4d** [comment] 2020-12-24 06:07
> hex codes for v1.05
> 
> "75 2D 33 C9 B8 01 00 00 00 0F A2 8B C8 C1 F9 08"
> 
> change "75" to "74" for AMD or "EB" for Intel (and AMD)

Does this work for the new 1.06, or does it change again?

**Comment by Benman2785** [comment] 2020-12-24 23:24
@l4d 
works with 1.06

**Closed** 2020-12-25 09:13 UTC
